title:              Terence Broad
email:              t.broad@gold.ac.uk
description:        Research blog
author:             Terence Broad
baseurl:            ""
url:                "https://blog.terencebroad.com"

# Social Profiles
twitter_username:   Terrybroad
github_username:    terrybroad
linkedin_username:  terence-broad-81350668

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
